[build]
  functions = "functions"
  publish = "."
  command = "npm install"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
